//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DbBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DbBase), typeof(System.Object));
		L.RegFunction("init", init);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			DbBase obj = (DbBase)ToLua.CheckObject(L, 1, typeof(DbBase));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			LuaTable arg1 = ToLua.CheckLuaTable(L, 3);
			obj.init(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

