//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NotiConstWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NotiConst), typeof(System.Object));
		L.RegFunction("New", _CreateNotiConst);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("START_UP", get_START_UP, null);
		L.RegVar("DISPATCH_MESSAGE", get_DISPATCH_MESSAGE, null);
		L.RegVar("UPDATE_MESSAGE", get_UPDATE_MESSAGE, null);
		L.RegVar("UPDATE_EXTRACT", get_UPDATE_EXTRACT, null);
		L.RegVar("UPDATE_DOWNLOAD", get_UPDATE_DOWNLOAD, null);
		L.RegVar("UPDATE_PROGRESS", get_UPDATE_PROGRESS, null);
		L.RegVar("REBOOT_GAME", get_REBOOT_GAME, null);
		L.RegVar("LOADING_START", get_LOADING_START, null);
		L.RegVar("LOADING_PROGRESS", get_LOADING_PROGRESS, null);
		L.RegVar("LOADING_END", get_LOADING_END, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNotiConst(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				NotiConst obj = new NotiConst();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: NotiConst.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_START_UP(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NotiConst.START_UP);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DISPATCH_MESSAGE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NotiConst.DISPATCH_MESSAGE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UPDATE_MESSAGE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NotiConst.UPDATE_MESSAGE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UPDATE_EXTRACT(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NotiConst.UPDATE_EXTRACT);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UPDATE_DOWNLOAD(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NotiConst.UPDATE_DOWNLOAD);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UPDATE_PROGRESS(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NotiConst.UPDATE_PROGRESS);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_REBOOT_GAME(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NotiConst.REBOOT_GAME);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LOADING_START(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NotiConst.LOADING_START);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LOADING_PROGRESS(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NotiConst.LOADING_PROGRESS);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LOADING_END(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, NotiConst.LOADING_END);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

