//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UITweener_DirectionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UITweener.Direction));
		L.RegVar("Reverse", get_Reverse, null);
		L.RegVar("Toggle", get_Toggle, null);
		L.RegVar("Forward", get_Forward, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Reverse(IntPtr L)
	{
		ToLua.Push(L, UITweener.Direction.Reverse);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Toggle(IntPtr L)
	{
		ToLua.Push(L, UITweener.Direction.Toggle);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Forward(IntPtr L)
	{
		ToLua.Push(L, UITweener.Direction.Forward);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UITweener.Direction o = (UITweener.Direction)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

